#
# Run Description goes here.
#
# -----------------------------------------------------------------------------
# OFTSWA Parameters
# -----------------------------------------------------------------------------
#
run:
  run_name: 'run1'
  preexisting_magmap_runname: ''
  preexisting_conflow_runname: ''
  date_start: '2015-01-01T00:00:00'
  date_end:   '2015-02-01T00:00:00'
  map_resolution:
    np: 1024
    nt: 512
  mpi_run_command: 'mpirun -bind-to none -np <NP>'
  mpi_num_procs: 1
  omp_num_threads: ''
#
# -----------------------------------------------------------------------------
# HipFT Parameters
# -----------------------------------------------------------------------------
#
hipft:
  run:  False
  overwrite:  False
  output_map_cadence_hr: 24
  output_map_flux_balance: False
  initial_map_filename: ''
  initial_map_mult_fac: 1.0
  data_assimilation_mult_fac: 1.0
  data_assimilation_balance_flux: True
  random_flux_lifetime: 0.3
  realization_combination_mode: 'sweep1d'
  realization_parameters:
    diffusion_coefs: [300.0]
    flow_attenuation_values: [500.0]
    data_assimilation_mu_limits: [0.1]
    data_assimilation_mu_powers: [4.0]
    data_assimilation_lat_limits: [0.0]
    random_flux_amounts: [150.0]
    flow_meridional_p1: [22.0]
    flow_meridional_p3: [11.0]
    flow_meridional_p5: [-28.0]
    flow_differential_p0: [46.0]
    flow_differential_p2: [-262.0]
    flow_differential_p4: [-379.0]
#
# -----------------------------------------------------------------------------
# HipFT Map Processing Parameters
# -----------------------------------------------------------------------------
#
output_map_processing:
  run: False
  overwrite:  False
  map_resolution_delta_deg:  1.0
  smoothing_factor: 1.0
  map_multiplier: 1.0
  make_wsa_dataset: False
#
# -----------------------------------------------------------------------------
# HipFT Post Processing Parameters
# -----------------------------------------------------------------------------
# This applies to both raw and processed maps if they exist
#
hipft_post_process:
  run:  True
  overwrite:  False
  history_plot_samples: 500
  history_plot_samples_markers: 20
  butterfly_averaging_width_hr: 0 
#
# -----------------------------------------------------------------------------
# ConFlow Parameters
# -----------------------------------------------------------------------------
#
conflow:
  run:  False
  overwrite:  False
#
# -----------------------------------------------------------------------------
# MagMAP Parameters
# -----------------------------------------------------------------------------
#
magmap:
  run:  False
  overwrite:  False
  update:  False
  map_cadence_hr: 1
  map_source: 'hmi_los'
#
